// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CarrierStats struct {
	Orders  int     `json:"orders"`
	Ranking float64 `json:"ranking"`
}

type NewCarrier struct {
	PublicID      string  `json:"public_id"`
	StorePublicID string  `json:"store_public_id"`
	Name          string  `json:"name"`
	Birthdate     string  `json:"birthdate"`
	Username      string  `json:"username"`
	Password      string  `json:"password"`
	MessageToken  *string `json:"message_token"`
	Phone         string  `json:"phone"`
}

type UpdateCarrier struct {
	Name          *string `json:"name"`
	Birthdate     *string `json:"birthdate"`
	StateDelivery *int    `json:"state_delivery"`
	State         *bool   `json:"state"`
	Username      *string `json:"username"`
	Password      *string `json:"password"`
	MessageToken  *string `json:"message_token"`
	Phone         *string `json:"phone"`
}
